name: Destroy Azure function App
on:
  repository_dispatch:
    types: delete_functionapp_app
jobs:
  delete-function-app:      
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      AZURE_FUNCTION_APP_NAME: "${{ github.event.client_payload.functionapp_name }}"
      AZURE_RESOURCE_GROUP: "${{ github.event.client_payload.resource_group }}"
      AZURE_SUBSCRIPTION: "${{ github.event.client_payload.subscription }}"
      AZURE_CLIENT_ID: "${{ github.event.client_payload.client_id }}"
      AZURE_CLIENT_SECRET: "${{ github.event.client_payload.client_secret }}"
      AZURE_TENANT_ID: "${{ github.event.client_payload.tenant_id }}"
    steps:    
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Azure
      run: |
        az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

    - name: Delete Azure function App
      run: |
        az functionapp delete --name $AZURE_FUNCTION_APP_NAME --resource-group $AZURE_RESOURCE_GROUP
    - name: Update Azure Function App Endpoints File
      run: |
        jq --arg funcationapp_name $AZURE_FUNCTION_APP_NAME 'del(.[($funcationapp_name)])' < .github/functions/functions.json > tmp_webapps.json && mv tmp_webapps.json .github/functions/functions.json
        git config --global user.email "siva.medapati@blueyonder.com"
        git config --global user.name "Siva Medapati"
        git config pull.rebase false
        git pull origin ${BRANCH}
        git add -f .github/functions/functions.json
        if [ -z "$(git status --porcelain)" ]; then 
          echo "Nothing to commit"
        else 
          git commit -m "update webapp endpoint"
          git push origin ${BRANCH}
        fi